ai_pre_process_running: true
ai_process_running: true
ai_process_paused: false
debugging: false
DataPath: /storage/gxt/purple_car_data
OutPath: /storage/gxt/Nov19_test
proj_str: '*CT_GS_loopCronTest_10C*'
cali_str: '*March5_cali*'
ob_dir: '*OB*'
ob_local_path:
- /storage/gxt/hype_test_data/March5_OB_5C_000
- /storage/gxt/hype_test_data/March5_OB_5C_001
- /storage/gxt/hype_test_data/March5_OB_5C_002
log_name: /storage/gxt/hype_test_output/logs/shimin_log.log
step: 3
QIthresh: 6
num_ini_ang: 3
Max_ang_num: 55
Angle_mode: golden
wav_idx_start:
- 270
- 500
wav_idx_end:
- 480
- 710
Z_START:
- 200
- 275
- 350
Z_NUM:
- 50
- 50
- 50
crop_cols:
- 2
- 492
load_paras:
  x_off: 2
  y_off: 2
  cent_x: 256
  cent_y: 256
  unused_pix_num: 1
  neighbor_pix_num: 3
  if_clean: true
  if_save_clean: true
  bound: 5
  correct_radius: 1
background_cali_paras:
  if_cali: true
  box_x:
  - 10
  - 10
  - 280
  - 280
  box_y:
  - 10
  - 450
  - 10
  - 450
  width: 20
  height: 200
center_offset: -4
num_threads: 248
T: 2.0
p: 1.2
sharpness: 0.0
snr_db: 30.0
max_iterations: 200
roi_info:
  roi_x: 10
  roi_y: 10
  roi_height: 462
  roi_width: 462
eva_paras:
  alpha: 0.6
  beta: 0.4
EIC_vals:
  run_title: HypeCT_test
  motor_pv: BL10:Mot:rot1
canny_paras:
  a: 0.3
  b: 0.7
  sigma: 4
hough_paras:
  line_length: 20
  line_gap: 10
SIM: false
experiment_title: November20_2024_CrushedRing_60Hz_1_8Angs_min
proton_charge: 2.5
scan_description: hyperCT run
number_of_obs: 3
ipts: 33531
number_of_runs_reduced_and_moved: 6
list_of_runs_reduced: null
